// Flowchart presets for FlowchartLab, modelled on the NCTB book's figures (ch5).
// Node: { id, type: start|end|io|process|decision|connector, text, col, row,
//         code? (C statements, process), read? [vars] (io input), print? [C exprs or "string" literals] (io output),
//         test? (C condition, decision), ask? (decision answered by the student),
//         next | yes | no (target ids), nextSide | yesSide | noSide ('down'|'left'|'right'), lane? (back-edge spacing) }
// vars: { name: 'int' | 'double' | { type, size } }

export const FLOWCHARTS = {
  college: {
    title: 'কলেজে যাওয়া (বইয়ের চিত্র ৫.৬)',
    vars: {},
    nodes: [
      { id: 's', type: 'start', text: 'শুরু', col: 0, row: 0, next: 'd' },
      { id: 'd', type: 'decision', text: 'সাইকেল ঠিক আছে?', col: 0, row: 1, ask: true, yes: 'bike', yesSide: 'right', no: 'money' },
      { id: 'bike', type: 'process', text: 'সাইকেল চালিয়ে\nকলেজে যাও', col: 1, row: 1, next: 'j' },
      { id: 'money', type: 'process', text: 'অভিভাবকের কাছ থেকে\nরিকশা ভাড়া নাও', col: 0, row: 2, next: 'rick' },
      { id: 'rick', type: 'process', text: 'রিকশা ভাড়া করে\nকলেজে যাও', col: 0, row: 3, next: 'j' },
      { id: 'j', type: 'connector', text: '', col: 0, row: 4, next: 'out' },
      { id: 'out', type: 'io', text: 'কলেজে পৌঁছে গিয়েছ', col: 0, row: 5, print: ['"কলেজে পৌঁছে গিয়েছ"'], next: 'e' },
      { id: 'e', type: 'end', text: 'শেষ', col: 0, row: 6 },
    ],
  },
  'c-to-f': {
    title: 'সেলসিয়াস থেকে ফারেনহাইট (বইয়ের চিত্র ৫.৭)',
    vars: { C: 'double', F: 'double' },
    input: '37',
    nodes: [
      { id: 's', type: 'start', text: 'শুরু', col: 0, row: 0, next: 'in' },
      { id: 'in', type: 'io', text: 'C-এর মান ইনপুট', col: 0, row: 1, read: ['C'], next: 'p' },
      { id: 'p', type: 'process', text: 'F = 9/5 × C + 32', col: 0, row: 2, code: 'F = 9.0 / 5 * C + 32;', next: 'out' },
      { id: 'out', type: 'io', text: 'F-এর মান প্রিন্ট', col: 0, row: 3, print: ['F'], next: 'e' },
      { id: 'e', type: 'end', text: 'শেষ', col: 0, row: 4 },
    ],
  },
  max2: {
    title: 'দুটি সংখ্যার তুলনা (বইয়ের চিত্র ৫.৮)',
    vars: { n1: 'int', n2: 'int' },
    nodes: [
      { id: 's', type: 'start', text: 'শুরু', col: 0, row: 0, next: 'p' },
      { id: 'p', type: 'process', text: 'n1 = 5, n2 = 7', col: 0, row: 1, code: 'n1 = 5; n2 = 7;', next: 'd1' },
      { id: 'd1', type: 'decision', text: 'n1 == n2?', col: 0, row: 2, test: 'n1 == n2', yes: 'eq', yesSide: 'right', no: 'd2' },
      { id: 'eq', type: 'io', text: 'n1 & n2 are equal', col: 1, row: 2, print: ['"n1 & n2 are equal"'], next: 'j' },
      { id: 'd2', type: 'decision', text: 'n1 > n2?', col: 0, row: 3, test: 'n1 > n2', yes: 'gt', yesSide: 'right', no: 'lt' },
      { id: 'gt', type: 'io', text: 'n1 is greater than n2', col: 1, row: 3, print: ['"n1 is greater than n2"'], next: 'j' },
      { id: 'lt', type: 'io', text: 'n1 is less than n2', col: 0, row: 4, print: ['"n1 is less than n2"'], next: 'j' },
      { id: 'j', type: 'connector', text: '', col: 0, row: 5, next: 'e' },
      { id: 'e', type: 'end', text: 'শেষ', col: 0, row: 6 },
    ],
  },
  count: {
    title: '1 থেকে 10 পর্যন্ত প্রিন্ট (বইয়ের চিত্র ৫.৯-এর মতো)',
    vars: { n: 'int' },
    nodes: [
      { id: 's', type: 'start', text: 'শুরু', col: 0, row: 0, next: 'p' },
      { id: 'p', type: 'process', text: 'n = 1', col: 0, row: 1, code: 'n = 1;', next: 'd' },
      { id: 'd', type: 'decision', text: 'n <= 10?', col: 0, row: 2, test: 'n <= 10', yes: 'out', no: 'e', noSide: 'right' },
      { id: 'out', type: 'io', text: 'n-এর মান প্রিন্ট', col: 0, row: 3, print: ['n'], next: 'inc' },
      { id: 'inc', type: 'process', text: 'n = n + 1', col: 0, row: 4, code: 'n = n + 1;', next: 'd', nextSide: 'left' },
      { id: 'e', type: 'end', text: 'শেষ', col: 1, row: 2 },
    ],
  },
  table: {
    title: 'n-এর নামতা (বইয়ের চিত্র ৫.১০)',
    vars: { n: 'int', i: 'int' },
    input: '5',
    nodes: [
      { id: 's', type: 'start', text: 'শুরু', col: 0, row: 0, next: 'in' },
      { id: 'in', type: 'io', text: 'n ইনপুট', col: 0, row: 1, read: ['n'], next: 'p' },
      { id: 'p', type: 'process', text: 'i = 1', col: 0, row: 2, code: 'i = 1;', next: 'd' },
      { id: 'd', type: 'decision', text: 'i <= 10?', col: 0, row: 3, test: 'i <= 10', yes: 'out', no: 'e', noSide: 'left' },
      { id: 'out', type: 'io', text: 'n, i ও n × i প্রিন্ট', col: 0, row: 4, print: ['n', '" x "', 'i', '" = "', 'n * i'], next: 'inc' },
      { id: 'inc', type: 'process', text: 'i = i + 1', col: 1, row: 4, code: 'i = i + 1;', next: 'd', nextSide: 'right' },
      { id: 'e', type: 'end', text: 'শেষ', col: 0, row: 6 },
    ],
  },
  'sum-odd': {
    title: '1 থেকে 500 পর্যন্ত বিজোড় সংখ্যার যোগফল (বইয়ের নিজে করি ৭)',
    vars: { sum: 'int', n: 'int' },
    nodes: [
      { id: 's', type: 'start', text: 'শুরু', col: 0, row: 0, next: 'p' },
      { id: 'p', type: 'process', text: 'sum = 0, n = 1', col: 0, row: 1, code: 'sum = 0; n = 1;', next: 'd' },
      { id: 'd', type: 'decision', text: 'n <= 500?', col: 0, row: 2, test: 'n <= 500', yes: 'add', no: 'out', noSide: 'right' },
      { id: 'add', type: 'process', text: 'sum = sum + n', col: 0, row: 3, code: 'sum = sum + n;', next: 'inc' },
      { id: 'inc', type: 'process', text: 'n = n + 2', col: 0, row: 4, code: 'n = n + 2;', next: 'd', nextSide: 'left' },
      { id: 'out', type: 'io', text: 'sum প্রিন্ট', col: 1, row: 3, print: ['sum'], next: 'e' },
      { id: 'e', type: 'end', text: 'শেষ', col: 1, row: 4 },
    ],
  },
  factorial: {
    title: 'n! (ফ্যাক্টরিয়াল)',
    vars: { n: 'int', i: 'int', fact: 'int' },
    input: '5',
    nodes: [
      { id: 's', type: 'start', text: 'শুরু', col: 0, row: 0, next: 'in' },
      { id: 'in', type: 'io', text: 'n ইনপুট', col: 0, row: 1, read: ['n'], next: 'p' },
      { id: 'p', type: 'process', text: 'fact = 1, i = 1', col: 0, row: 2, code: 'fact = 1; i = 1;', next: 'd' },
      { id: 'd', type: 'decision', text: 'i <= n?', col: 0, row: 3, test: 'i <= n', yes: 'mul', no: 'out', noSide: 'right' },
      { id: 'mul', type: 'process', text: 'fact = fact × i', col: 0, row: 4, code: 'fact = fact * i;', next: 'inc' },
      { id: 'inc', type: 'process', text: 'i = i + 1', col: 0, row: 5, code: 'i = i + 1;', next: 'd', nextSide: 'left' },
      { id: 'out', type: 'io', text: 'fact প্রিন্ট', col: 1, row: 4, print: ['fact'], next: 'e' },
      { id: 'e', type: 'end', text: 'শেষ', col: 1, row: 5 },
    ],
  },
  'even-odd': {
    title: 'জোড় না বিজোড়',
    vars: { n: 'int' },
    input: '7',
    nodes: [
      { id: 's', type: 'start', text: 'শুরু', col: 0, row: 0, next: 'in' },
      { id: 'in', type: 'io', text: 'n ইনপুট', col: 0, row: 1, read: ['n'], next: 'd' },
      { id: 'd', type: 'decision', text: 'n % 2 == 0?', col: 0, row: 2, test: 'n % 2 == 0', yes: 'ev', yesSide: 'left', no: 'od', noSide: 'right' },
      { id: 'ev', type: 'io', text: '"Even" প্রিন্ট', col: -1, row: 3, print: ['"Even"'], next: 'j' },
      { id: 'od', type: 'io', text: '"Odd" প্রিন্ট', col: 1, row: 3, print: ['"Odd"'], next: 'j' },
      { id: 'j', type: 'connector', text: '', col: 0, row: 4, next: 'e' },
      { id: 'e', type: 'end', text: 'শেষ', col: 0, row: 5 },
    ],
  },
  max3: {
    title: 'তিনটি সংখ্যার মধ্যে বড়টি',
    vars: { a: 'int', b: 'int', c: 'int' },
    input: '12 45 30',
    nodes: [
      { id: 's', type: 'start', text: 'শুরু', col: 0, row: 0, next: 'in' },
      { id: 'in', type: 'io', text: 'a, b, c ইনপুট', col: 0, row: 1, read: ['a', 'b', 'c'], next: 'd1' },
      { id: 'd1', type: 'decision', text: 'a > b?', col: 0, row: 2, test: 'a > b', yes: 'd2', yesSide: 'left', no: 'd3', noSide: 'right' },
      { id: 'd2', type: 'decision', text: 'a > c?', col: -1, row: 3, test: 'a > c', yes: 'pa', no: 'pc1', noSide: 'right' },
      { id: 'd3', type: 'decision', text: 'b > c?', col: 1, row: 3, test: 'b > c', yes: 'pb', no: 'pc2', noSide: 'right' },
      { id: 'pa', type: 'io', text: 'a প্রিন্ট', col: -1, row: 4, print: ['a'], next: 'j' },
      { id: 'pc1', type: 'io', text: 'c প্রিন্ট', col: 0, row: 4, print: ['c'], next: 'j' },
      { id: 'pb', type: 'io', text: 'b প্রিন্ট', col: 1, row: 4, print: ['b'], next: 'j' },
      { id: 'pc2', type: 'io', text: 'c প্রিন্ট', col: 2, row: 4, print: ['c'], next: 'j' },
      { id: 'j', type: 'connector', text: '', col: 0, row: 5, next: 'e' },
      { id: 'e', type: 'end', text: 'শেষ', col: 0, row: 6 },
    ],
  },
  search: {
    title: 'অ্যারেতে সংখ্যা খোঁজা (বইয়ের চিত্র ৫.১২)',
    vars: { ara: { type: 'int', size: 5 }, n: 'int', key: 'int', i: 'int' },
    init: { ara: [10, 25, 7, 40, 18], n: 5 },
    input: '40',
    nodes: [
      { id: 's', type: 'start', text: 'শুরু', col: 0, row: 0, next: 'in' },
      { id: 'in', type: 'io', text: 'key ইনপুট', col: 0, row: 1, read: ['key'], next: 'p' },
      { id: 'p', type: 'process', text: 'i = 0', col: 0, row: 2, code: 'i = 0;', next: 'd1' },
      { id: 'd1', type: 'decision', text: 'i < n?', col: 0, row: 3, test: 'i < n', yes: 'd2', no: 'j1', noSide: 'left' },
      { id: 'd2', type: 'decision', text: 'ara[i] == key?', col: 0, row: 4, test: 'ara[i] == key', yes: 'found', no: 'inc', noSide: 'right' },
      { id: 'inc', type: 'process', text: 'i += 1', col: 1, row: 4, code: 'i += 1;', next: 'd1', nextSide: 'right' },
      { id: 'found', type: 'io', text: 'প্রিন্ট Found!', col: 0, row: 5, print: ['"Found!"'], next: 'j1' },
      { id: 'j1', type: 'connector', text: '১', col: 0, row: 6, next: 'd3' },
      { id: 'd3', type: 'decision', text: 'i == n?', col: 0, row: 7, test: 'i == n', yes: 'nf', yesSide: 'right', no: 'j2' },
      { id: 'nf', type: 'io', text: 'প্রিন্ট Not found!', col: 1, row: 7, print: ['"Not found!"'], next: 'j2' },
      { id: 'j2', type: 'connector', text: '২', col: 0, row: 8, next: 'e' },
      { id: 'e', type: 'end', text: 'শেষ', col: 0, row: 9 },
    ],
  },
};
